//! gRPC Protocol Buffer definitions
//!
//! This module includes auto-generated code from `proto/meta.proto`.
//! The code is generated by tonic-build during compilation and placed in OUT_DIR.
//!
//! **DO NOT EDIT THIS FILE OR THE GENERATED CODE**
//!
//! To modify the gRPC interface:
//! 1. Edit `proto/meta.proto`
//! 2. Run `cargo build` to regenerate the code
//!
//! The `tonic::include_proto!` macro will automatically include the generated code
//! from the build output directory.

// Include the auto-generated protobuf code
// The package name "slayerfs.meta" matches the package declaration in proto/meta.proto
tonic::include_proto!("slayerfs.meta");
