// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileAttr {
    #[prost(int64, tag = "1")]
    pub ino: i64,
    #[prost(uint64, tag = "2")]
    pub size: u64,
    #[prost(enumeration = "FileType", tag = "3")]
    pub kind: i32,
    #[prost(uint32, tag = "4")]
    pub mode: u32,
    #[prost(uint32, tag = "5")]
    pub uid: u32,
    #[prost(uint32, tag = "6")]
    pub gid: u32,
    #[prost(int64, tag = "7")]
    pub atime: i64,
    #[prost(int64, tag = "8")]
    pub mtime: i64,
    #[prost(int64, tag = "9")]
    pub ctime: i64,
    #[prost(uint32, tag = "10")]
    pub nlink: u32,
    #[prost(uint64, tag = "11")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub ino: i64,
    #[prost(enumeration = "FileType", tag = "3")]
    pub kind: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InitializeRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InitializeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetRootInoRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetRootInoResponse {
    #[prost(int64, tag = "1")]
    pub ino: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAttrRequest {
    #[prost(int64, tag = "1")]
    pub ino: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAttrResponse {
    #[prost(message, optional, tag = "1")]
    pub attr: ::core::option::Option<FileAttr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAttrBatchRequest {
    #[prost(int64, repeated, tag = "1")]
    pub inos: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAttrBatchResponse {
    #[prost(message, repeated, tag = "1")]
    pub attrs: ::prost::alloc::vec::Vec<AttrPair>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AttrPair {
    #[prost(int64, tag = "1")]
    pub ino: i64,
    #[prost(message, optional, tag = "2")]
    pub attr: ::core::option::Option<FileAttr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupRequest {
    #[prost(int64, tag = "1")]
    pub parent: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LookupResponse {
    #[prost(int64, tag = "1")]
    pub ino: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReaddirRequest {
    #[prost(int64, tag = "1")]
    pub ino: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReaddirResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<DirEntry>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReaddirPlusRequest {
    #[prost(int64, tag = "1")]
    pub ino: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReaddirPlusResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<DirEntryPlus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirEntryPlus {
    #[prost(message, optional, tag = "1")]
    pub entry: ::core::option::Option<DirEntry>,
    #[prost(message, optional, tag = "2")]
    pub attr: ::core::option::Option<FileAttr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRequest {
    #[prost(int64, tag = "1")]
    pub parent: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "FileType", tag = "3")]
    pub kind: i32,
    #[prost(uint32, tag = "4")]
    pub mode: u32,
    #[prost(uint32, tag = "5")]
    pub uid: u32,
    #[prost(uint32, tag = "6")]
    pub gid: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateResponse {
    #[prost(int64, tag = "1")]
    pub ino: i64,
    #[prost(message, optional, tag = "2")]
    pub attr: ::core::option::Option<FileAttr>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetAttrRequest {
    #[prost(int64, tag = "1")]
    pub ino: i64,
    #[prost(uint64, optional, tag = "2")]
    pub size: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "3")]
    pub mode: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub uid: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub gid: ::core::option::Option<u32>,
    #[prost(int64, optional, tag = "6")]
    pub atime: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "7")]
    pub mtime: ::core::option::Option<i64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetAttrResponse {
    #[prost(message, optional, tag = "1")]
    pub attr: ::core::option::Option<FileAttr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenameRequest {
    #[prost(int64, tag = "1")]
    pub old_parent: i64,
    #[prost(string, tag = "2")]
    pub old_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub new_parent: i64,
    #[prost(string, tag = "4")]
    pub new_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RenameResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlinkRequest {
    #[prost(int64, tag = "1")]
    pub parent: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnlinkResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RmdirRequest {
    #[prost(int64, tag = "1")]
    pub parent: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RmdirResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileType {
    Unspecified = 0,
    File = 1,
    Dir = 2,
}
impl FileType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FILE_TYPE_UNSPECIFIED",
            Self::File => "FILE_TYPE_FILE",
            Self::Dir => "FILE_TYPE_DIR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FILE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "FILE_TYPE_FILE" => Some(Self::File),
            "FILE_TYPE_DIR" => Some(Self::Dir),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod meta_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Metadata Service
    #[derive(Debug, Clone)]
    pub struct MetaServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MetaServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MetaServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MetaServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MetaServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Initialize the metadata store
        pub async fn initialize(
            &mut self,
            request: impl tonic::IntoRequest<super::InitializeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InitializeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/Initialize",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "Initialize"));
            self.inner.unary(req, path, codec).await
        }
        /// Get root inode
        pub async fn get_root_ino(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRootInoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRootInoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/GetRootIno",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "GetRootIno"));
            self.inner.unary(req, path, codec).await
        }
        /// Get file attributes
        pub async fn get_attr(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAttrRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAttrResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/GetAttr",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "GetAttr"));
            self.inner.unary(req, path, codec).await
        }
        /// Get attributes for multiple inodes (batch)
        pub async fn get_attr_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAttrBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAttrBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/GetAttrBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "GetAttrBatch"));
            self.inner.unary(req, path, codec).await
        }
        /// Look up directory entry by name
        pub async fn lookup(
            &mut self,
            request: impl tonic::IntoRequest<super::LookupRequest>,
        ) -> std::result::Result<tonic::Response<super::LookupResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/Lookup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "Lookup"));
            self.inner.unary(req, path, codec).await
        }
        /// Read directory entries
        pub async fn readdir(
            &mut self,
            request: impl tonic::IntoRequest<super::ReaddirRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReaddirResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/Readdir",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "Readdir"));
            self.inner.unary(req, path, codec).await
        }
        /// Read directory entries with attributes (optimized)
        pub async fn readdir_plus(
            &mut self,
            request: impl tonic::IntoRequest<super::ReaddirPlusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReaddirPlusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/ReaddirPlus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "ReaddirPlus"));
            self.inner.unary(req, path, codec).await
        }
        /// Create file or directory
        pub async fn create(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateRequest>,
        ) -> std::result::Result<tonic::Response<super::CreateResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/Create",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "Create"));
            self.inner.unary(req, path, codec).await
        }
        /// Set file attributes
        pub async fn set_attr(
            &mut self,
            request: impl tonic::IntoRequest<super::SetAttrRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetAttrResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/SetAttr",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "SetAttr"));
            self.inner.unary(req, path, codec).await
        }
        /// Rename/move file or directory
        pub async fn rename(
            &mut self,
            request: impl tonic::IntoRequest<super::RenameRequest>,
        ) -> std::result::Result<tonic::Response<super::RenameResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/Rename",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "Rename"));
            self.inner.unary(req, path, codec).await
        }
        /// Remove file
        pub async fn unlink(
            &mut self,
            request: impl tonic::IntoRequest<super::UnlinkRequest>,
        ) -> std::result::Result<tonic::Response<super::UnlinkResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/Unlink",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "Unlink"));
            self.inner.unary(req, path, codec).await
        }
        /// Remove directory
        pub async fn rmdir(
            &mut self,
            request: impl tonic::IntoRequest<super::RmdirRequest>,
        ) -> std::result::Result<tonic::Response<super::RmdirResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/slayerfs.meta.MetaService/Rmdir",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("slayerfs.meta.MetaService", "Rmdir"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod meta_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MetaServiceServer.
    #[async_trait]
    pub trait MetaService: std::marker::Send + std::marker::Sync + 'static {
        /// Initialize the metadata store
        async fn initialize(
            &self,
            request: tonic::Request<super::InitializeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InitializeResponse>,
            tonic::Status,
        >;
        /// Get root inode
        async fn get_root_ino(
            &self,
            request: tonic::Request<super::GetRootInoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRootInoResponse>,
            tonic::Status,
        >;
        /// Get file attributes
        async fn get_attr(
            &self,
            request: tonic::Request<super::GetAttrRequest>,
        ) -> std::result::Result<tonic::Response<super::GetAttrResponse>, tonic::Status>;
        /// Get attributes for multiple inodes (batch)
        async fn get_attr_batch(
            &self,
            request: tonic::Request<super::GetAttrBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAttrBatchResponse>,
            tonic::Status,
        >;
        /// Look up directory entry by name
        async fn lookup(
            &self,
            request: tonic::Request<super::LookupRequest>,
        ) -> std::result::Result<tonic::Response<super::LookupResponse>, tonic::Status>;
        /// Read directory entries
        async fn readdir(
            &self,
            request: tonic::Request<super::ReaddirRequest>,
        ) -> std::result::Result<tonic::Response<super::ReaddirResponse>, tonic::Status>;
        /// Read directory entries with attributes (optimized)
        async fn readdir_plus(
            &self,
            request: tonic::Request<super::ReaddirPlusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReaddirPlusResponse>,
            tonic::Status,
        >;
        /// Create file or directory
        async fn create(
            &self,
            request: tonic::Request<super::CreateRequest>,
        ) -> std::result::Result<tonic::Response<super::CreateResponse>, tonic::Status>;
        /// Set file attributes
        async fn set_attr(
            &self,
            request: tonic::Request<super::SetAttrRequest>,
        ) -> std::result::Result<tonic::Response<super::SetAttrResponse>, tonic::Status>;
        /// Rename/move file or directory
        async fn rename(
            &self,
            request: tonic::Request<super::RenameRequest>,
        ) -> std::result::Result<tonic::Response<super::RenameResponse>, tonic::Status>;
        /// Remove file
        async fn unlink(
            &self,
            request: tonic::Request<super::UnlinkRequest>,
        ) -> std::result::Result<tonic::Response<super::UnlinkResponse>, tonic::Status>;
        /// Remove directory
        async fn rmdir(
            &self,
            request: tonic::Request<super::RmdirRequest>,
        ) -> std::result::Result<tonic::Response<super::RmdirResponse>, tonic::Status>;
    }
    /// Metadata Service
    #[derive(Debug)]
    pub struct MetaServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MetaServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MetaServiceServer<T>
    where
        T: MetaService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/slayerfs.meta.MetaService/Initialize" => {
                    #[allow(non_camel_case_types)]
                    struct InitializeSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::InitializeRequest>
                    for InitializeSvc<T> {
                        type Response = super::InitializeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InitializeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::initialize(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InitializeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/GetRootIno" => {
                    #[allow(non_camel_case_types)]
                    struct GetRootInoSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::GetRootInoRequest>
                    for GetRootInoSvc<T> {
                        type Response = super::GetRootInoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRootInoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::get_root_ino(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRootInoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/GetAttr" => {
                    #[allow(non_camel_case_types)]
                    struct GetAttrSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::GetAttrRequest>
                    for GetAttrSvc<T> {
                        type Response = super::GetAttrResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAttrRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::get_attr(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAttrSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/GetAttrBatch" => {
                    #[allow(non_camel_case_types)]
                    struct GetAttrBatchSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::GetAttrBatchRequest>
                    for GetAttrBatchSvc<T> {
                        type Response = super::GetAttrBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAttrBatchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::get_attr_batch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAttrBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/Lookup" => {
                    #[allow(non_camel_case_types)]
                    struct LookupSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::LookupRequest>
                    for LookupSvc<T> {
                        type Response = super::LookupResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LookupRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::lookup(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LookupSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/Readdir" => {
                    #[allow(non_camel_case_types)]
                    struct ReaddirSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::ReaddirRequest>
                    for ReaddirSvc<T> {
                        type Response = super::ReaddirResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReaddirRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::readdir(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReaddirSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/ReaddirPlus" => {
                    #[allow(non_camel_case_types)]
                    struct ReaddirPlusSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::ReaddirPlusRequest>
                    for ReaddirPlusSvc<T> {
                        type Response = super::ReaddirPlusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReaddirPlusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::readdir_plus(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReaddirPlusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/Create" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::CreateRequest>
                    for CreateSvc<T> {
                        type Response = super::CreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/SetAttr" => {
                    #[allow(non_camel_case_types)]
                    struct SetAttrSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::SetAttrRequest>
                    for SetAttrSvc<T> {
                        type Response = super::SetAttrResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetAttrRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::set_attr(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetAttrSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/Rename" => {
                    #[allow(non_camel_case_types)]
                    struct RenameSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::RenameRequest>
                    for RenameSvc<T> {
                        type Response = super::RenameResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RenameRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::rename(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RenameSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/Unlink" => {
                    #[allow(non_camel_case_types)]
                    struct UnlinkSvc<T: MetaService>(pub Arc<T>);
                    impl<
                        T: MetaService,
                    > tonic::server::UnaryService<super::UnlinkRequest>
                    for UnlinkSvc<T> {
                        type Response = super::UnlinkResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnlinkRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::unlink(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnlinkSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/slayerfs.meta.MetaService/Rmdir" => {
                    #[allow(non_camel_case_types)]
                    struct RmdirSvc<T: MetaService>(pub Arc<T>);
                    impl<T: MetaService> tonic::server::UnaryService<super::RmdirRequest>
                    for RmdirSvc<T> {
                        type Response = super::RmdirResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RmdirRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MetaService>::rmdir(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RmdirSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MetaServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "slayerfs.meta.MetaService";
    impl<T> tonic::server::NamedService for MetaServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
